services:
  bot:
    build:
      context: .
      dockerfile: DockerFile
    container_name: tgp-vpn-bot
    env_file: .env
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/app/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
